netwin:
  ip: '172.24.28.157'
  interfaces:
    netwin_backend:
      port: 80
      address_service:
        context: '/ns-jvt-webservice-om-v1-0/JVTOrderManagementSessionWebService'


db:
  ip: '10.51.160.50'

bit:
  host: hosts.arqosfortuna.ip
  bit_user: 'webuser'
  username: hosts.arqosfortuna.username
  password: hosts.arqosfortuna.password
  #bit_path: '/opt/ptin/bit/bin'
  bit_path: '/webaplic/bit/bin'
  

vts_core:
  host: '10.51.163.123'
  port: 8081
  site: 'SP'
  context: '/vts/oi'

agendamento:
  lotes: 10
  arquivos: 10

jenkins:
  ip: "10.51.163.30"
  hostname: 'jenkinsbr'
  username: 'ptin_admin'
  password: 'ptin_admin'
  shub_context: '/fortuna'
  shub_port: 4568
  interfaces:
    sinatra:
      type: http
      context: '/fortuna'
      port: 4568
