oracle_login:
  username: 'NETWINOI'
  password: 'netwinoi'

shild:
  username: 'ptikpidev'
  password: 'ptikpidev'


sqa: &sqa
  username: 'SQA'
  password: 'sqa'

oracle_db:
  ip: hosts.db.ip
  port: 1521
  sid: 'invevl'
  tnsnames: "(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.51.160.186)(PORT = 1521)))(CONNECT_DATA = (SERVICE_NAME = invevl)))"
#  tnsnames: "(DESCRIPTION =  (ADDRESS_LIST = (ADDRESS =  (PROTOCOL = TCP) (HOST = 10.51.163.31) (PORT = 1521)) ) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = invevl)))"


global_values:
  max_attempts: 10

oracle_db_2:
  ip: hosts.db.ip
  port: 1521
  sid: 'bssdb'
  tnsnames: "(DESCRIPTION = ( ADDRESS_LIST = ( ADDRESS = (PROTOCOL = TCP)(HOST = 10.51.160.50)(PORT = 1521)))( CONNECT_DATA = (SERVICE_NAME = bssdb)))"
